[versions]
indra = "3.1.3"

[plugins]
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
indra = { id = "net.kyori.indra", version.ref = "indra" }
indraCheckstyle = { id = "net.kyori.indra.checkstyle", version.ref = "indra" }
indraPublishing = { id = "net.kyori.indra.publishing", version.ref = "indra" }
indraPublishingSonatype = { id = "net.kyori.indra.publishing.sonatype", version.ref = "indra" }
errorprone = { id = "net.ltgt.errorprone", version = "3.1.0" }

[libraries]
contractValidator = { module = "ca.stellardrift:contract-validator", version = "1.0.1" }
stylecheck = { module = "ca.stellardrift:stylecheck", version = "0.2.1" }
errorProneCore = { module = "com.google.errorprone:error_prone_core", version = "2.24.1" }
guavaTestlib = { module = "com.google.guava:guava-testlib", version = "33.0.0-jre" }
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version = "24.1.0" }
jspecify = { module = "org.jspecify:jspecify", version = "0.3.0" }
junit-bom = { module = "org.junit:junit-bom", version = "5.10.1" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
